import {pageLoad} from './pageLoad';
import './styles.css';
import CaliforniaRolls from './images/CaliforniaRolls.jpg';
import Gunkan from './images/Gunkan.jpg';
import Maki from './images/Maki.jpg';
import MisoSoup from './images/MisoSoup.jpg';
import SalmonNigiri from './images/SalmonNigiri.jpg';
import Sashimi from './images/Sashimi.jpg';
import SoysSauce from './images/SoySauce.jpg';
import SushiPlate from './images/SushiPlate.jpg';
import Wasabi from './images/Wasabi.jpg';
pageLoad();